[package]
name = "tethys"
version = "5.0.0"
edition = "2024"

[dependencies]

[dependencies.elf]
version = "0.8.0"
default-features = false
features = ["alloc", "to_str"]

[dependencies.ostd]
version = "0.17.0"

[workspace]
exclude = ["target/osdk/base", "target/osdk/test-base"]
